version: '3.7'
# TO SCALE WORKERs docker-compose scale celery_worker_default=5
services:
  api:
    image: smtv-api:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: smtv-api
    command: /wait-for-it.sh api-postgres:5432 -- bash -c "sleep 1; migrate && check_environment && start_service"
    restart: always
    env_file:
      - services-variables.env
    ports:
      - 81:80
    depends_on:
      - api-postgres
      - localstack
    volumes:
      - ./src:/srv

  celery_worker_template: &celery_worker_template # anchor to reuse dev/prod
    image: smtv-worker-celery
    build:
      context: .
      dockerfile: Dockerfile
      target: smtv-worker-celery
    env_file:
      - services-variables.env
    entrypoint: celery
    # command: -A tasks worker --loglevel=debug
    volumes:
      - ./src:/srv
      - ./fstorage:/fstorage # TODO remove after integrated with S3
    links:
      - redis
      - api-postgres
    depends_on:
      - redis
      - api-postgres # in'n'out to pg

  # DEV celery with code reloading
  celery_worker_default:
    <<: *celery_worker_template
    # entrypoint: bash -c "sleep 3600"
    entrypoint: watchmedo
    command: auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks worker --loglevel=debug -n default-worker@%h --workdir /srv/smtv_api/celery_service/


  # PROD-like without code reloading
  # celery_worker:
  #   <<: *celery_worker_template
  #   entrypoint: celery
  #   command: -A <module-name> worker --loglevel=debug
  #   restart: always

  flower:
    <<: *celery_worker_template
    command: -A tasks flower --port=5555 --workdir /srv/smtv_api/celery_service/
    ports: 
      - 5555:5555

# Rest of svcs - db, cache, fs
  api-postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  redis:
    hostname: redis
    image: redis:5.0.7
    ports:
      - 6379:6379

  localstack:
    image: localstack/localstack:latest
    restart: always
    ports:
      - 4572:4572
      - 18888:8888
    environment:
      - SERVICES=s3
      - PORT_WEB_UI=8888
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./fstorage:/tmp/localstack