#!/bin/bash -e

if [ "$#" -eq 0 ]; then
    echo "Usage - create_alembic_revision name_of_the_revision (other params for alembic)"
    exit 1
fi

ROOT_PATH=$(git rev-parse --show-toplevel)
POSTGRES_NAME="test-postgres"

# rm rf if test postgres running
# https://forums.docker.com/t/implement-no-run-if-empty-or-similar-feature-in-the-docker-command/47487
docker ps -aq -f name=$POSTGRES_NAME | xargs --no-run-if-empty docker rm -f


if [ -z $(docker ps --format "{{.Names}}" | grep $POSTGRES_NAME) ]; then
    docker run -d \
        -e POSTGRES_HOST_AUTH_METHOD=trust \
        --name $POSTGRES_NAME \
        --restart=always \
        postgres:12

    sleep 1
fi

docker run --rm \
    -e POSTGRES_PASSWORD=postgres \
    -e API_DATABASE_URL=postgresql://postgres:postgres@$POSTGRES_NAME:5432/postgres \
    --env-file ${ROOT_PATH}/services-variables.env \
    --link $POSTGRES_NAME:$POSTGRES_NAME \
    -v ${ROOT_PATH}/src:/srv \
    smtv-api:dev \
    migrate

docker run --rm \
	-e POSTGRES_PASSWORD=postgres \
    -e API_DATABASE_URL=postgresql://postgres:postgres@$POSTGRES_NAME:5432/postgres \
    --link $POSTGRES_NAME:$POSTGRES_NAME \
    -v ${ROOT_PATH}/src:/srv \
    smtv-api:dev \
    alembic revision -m $1 --autogenerate ${@:2}

docker stop $POSTGRES_NAME 1>/dev/null
docker rm $POSTGRES_NAME 1>/dev/null
